# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Michael A Osborne
tagline:          'Associate Professor in Machine Learning'
description:      'Associate Professor in Machine Learning at the
                  <a href="http://www.ox.ac.uk">University of Oxford</a>'
url:
baseurl:

author:
  name:           'Michael Osborne'
  url:            http://www.robots.ox.ac.uk/~mosb

paginate:         1


github:
  repo:           https://github.com/mosb/robots-www
